
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.185.98:3306/yu_ai_code_mother
    username: yu_ai_code_mother_user
    password: w2004611
  # redis
  data:
    redis:
      host: 119.29.185.98
      port: 6379
      database: 0
      password: redis_EBQEAm
      ttl: 3600
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-805eb66b7a1545a8b6f6ca76d4311962
      model-name: qwen-flash
      max-tokens: 8192
      log-requests: false
      log-responses: false
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-805eb66b7a1545a8b6f6ca76d4311962
      model-name: qwen-plus-latest
      max-tokens: 8192
      log-requests: false
      log-responses: false
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-805eb66b7a1545a8b6f6ca76d4311962
      model-name: qwen-plus-latest
      max-tokens: 8192
      temperature: 0.1
      log-requests: false
      log-responses: false
    # 智能路由 AI 模型配置
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-805eb66b7a1545a8b6f6ca76d4311962
      model-name: qwen-flash
      max-tokens: 100
      log-requests: false
      log-responses: false
# 生产环境关闭日志
mybatis-flex:
  configuration:
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
# 部署路径
code:
  deploy-host: http://119.29.185.98/dist
